### PR TITLE
Updated validator to `0.18`

### PR DESCRIPTION
**Pull request by ranger-ross**
I updated the [validator](https://docs.rs/validator/latest/validator/) crate to `0.18`. 

Should resolve https://github.com/rambler-digital-solutions/actix-web-validator/issues/51

---

Note: That this is a breaking change :sweat_smile:

### CODE REVIEW

**Comment by mrsarm** [comment]
I'm trying to update to the latest "validator" and "active-web-validator" crates, and testing this patch in my project https://github.com/mrsarm/rust-actix-contrib-rest makes the build and tests to pass again.

**Comment by mrsarm** [comment]
It looks like everyone who worked on the project has left the company, leaving the project unmaintained, so maybe the only solution is to fork it :disappointed:.

**Comment by ranger-ross** [comment]
> It looks like everyone who worked on the project has left the company, leaving the project unmaintained, so maybe the only solution is to fork it 😞.

Yeah, I think I came to that realization when I saw the recent commit history for this repository :sweat_smile: 

I have been working on a replacement for this library (not a fork) to address some of the pain points I have felt using this library. 
https://crates.io/crates/actix-web-validation 
I suppose you could use this one if this library goes unmaintained.

**Comment by lewsmith** [comment]
> > It looks like everyone who worked on the project has left the company, leaving the project unmaintained, so maybe the only solution is to fork it 😞.
> 
> Yeah, I think I came to that realization when I saw the recent commit history for this repository 😅
> 
> I have been working on a replacement for this library (not a fork) to address some of the pain points I have felt using this library. https://crates.io/crates/actix-web-validation I suppose you could use this one if this library goes unmaintained.

Nice. I've got to admit, I much prefer the way you are using the `Validated()` wrapper, when compared to how actix-web-validator uses the same naming as actix-web's extractors. More verbose so you can clearly see what's being validated. :+1:

**Review by singulared — APPROVED** [review]

**Pull request merged**
